### PR TITLE
Bind/run interface to CodeGen

### PR DESCRIPTION
**Pull request by bertmaher**

### CODE REVIEW

**Comment by bertmaher** [comment]
Curious to get y'all's thoughts on this interface.  It seems like something we can make common across all backends.

**Comment by resistor** [comment]
This is intended to replace stuff like value()?

**Comment by bertmaher** [comment]
Yeah, exactly.  I want a common interface for the backends (interp, cpu, gpu) to bind args and run the compiled kernel.

**Comment by bertmaher** [comment]
I've moved LLVMCodeGen over to this interface (will push an update to this PR in a second).  Something that is awkward is that `bind()` doesn't really need to take a Buffer argument for the llvm codegen.  Args are already defined by their order in the kernel's argv wrapper.  But the IR interpreter actually uses the bound buffers to setup Var->data mappings.  Hm.

**Comment by bertmaher** [comment]
Also bind/run is maybe a bad API, since I just coded up a silly bug by forgetting to clear the bindings after a run, leading to much hilarity when trying to reuse a compiled kernel.

**Comment by bertmaher** [comment]
Going to go ahead and land this to keep moving forward.  Definitely open to changing this design.

**Pull request merged**
